multitenancy/urls.py
from django.urls import path, include

# from django.conf.urls import url
from .admin import team_urls
from .admin import customer_urls
from .admin import urls as admin_urls
from .profiles import urls as profile_urls
from .subscriptions import urls as subscription_urls
from .users import urls as users_urls
from .apps import urls as apps_urls
from .settings import urls as settings_urls
from .billing import urls as billing_urls
from .order import urls as order_urls
from . import api


urlpatterns = [
    path("admin/", include(admin_urls)),
    path("admin/", include(users_urls)),
    path("admin/", include(apps_urls)),
    path("admin/", include(subscription_urls)),
    path("admin/", include(billing_urls)),
    path("admin/", include(order_urls)),
    path("admin/", include(settings_urls)),
    path("dashboard/", include(customer_urls)),
    path("admin/", include(team_urls)),
    path("admin/profiles/", include(profile_urls)),
    path("api/", include(api)),
]

multitenancy/apps/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.conf import settings
from django.db import models, transaction

from django.db.models import Q, Sum
from django_tenants.models import DomainMixin
from datetime import datetime, timedelta
from tenant_users.tenants.models import TenantBase
from django_tenants.utils import get_tenant_type_choices

from multitenancy.subscriptions.models import Plan, Subscription


DEFAULT_TYPE = "personal"


def get_types():
    # remove the plublic tenant type from list
    items = get_tenant_type_choices()
    items.pop(0)
    return items


class TenantQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.all()
        lookups = (
            Q(name__icontains=query)
            | Q(id__contains=query)
            | Q(type__iexact=query)
            | Q(owner__id__icontains=query)
            | Q(owner__email__icontains=query)
            | Q(owner__username__icontains=query)
        )
        return self.filter(lookups)

    def filter_by_plan(self, plan):
        filter = self.filter(type=plan)
        return filter

    def active(self):
        return self.filter(subscription__is_active=True)


class TenantManager(models.Manager):
    def get_queryset(self):
        return TenantQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)

    def filter_by_plan(self, plan):
        return self.get_queryset().filter_by_plan(plan=plan)

    def active(self):
        return self.get_queryset().active()


DEFAULT_TYPE = "default"


class Tenant(TenantBase):
    id = models.AutoField(primary_key=True, auto_created=True)
    type = models.CharField(max_length=200, default=DEFAULT_TYPE, choices=get_types())
    name = models.CharField(max_length=100)
    is_template = models.BooleanField(default=True)
    plan = models.ForeignKey(
        Plan, null=True, on_delete=models.PROTECT, related_name="tenants"
    )
    description = models.TextField(max_length=200)
    subscription = models.OneToOneField(
        Subscription,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="tenants",
    )
    # paid_until = models.DateField()
    trail_duration = models.IntegerField(default=0)
    on_trial = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)
    objects = TenantManager()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ["id", "name"]
        verbose_name = settings.TENANT_DISPLAY_NAME
        verbose_name_plural = settings.TENANT_DISPLAY_NAME_PLURAL

    @classmethod
    def create_tenant(
        cls,
        name,
        type,
        is_template,
        description,
        trail_duration,
        owner,
        subscription_plan,
    ):
        subscription = Subscription.objects.create(plan=subscription_plan, owner=owner)
        tenant = cls.objects.create(
            name=name,
            type=type,
            is_template=is_template,
            description=description,
            trail_duration=trail_duration,
            subscription=subscription,
            owner=owner,
        )
        return tenant

    @transaction.atomic
    def create_tenant_with_subscription(self, plan, **kwargs):
        subscription = Subscription.objects.create(plan=plan)
        kwargs["subscription"] = subscription
        tenant = Tenant.objects.create(**kwargs)
        return tenant

    @classmethod
    def total_revenue(cls):
        revenue = cls.objects.aggregate(total_revenue=Sum("plan__price"))[
            "total_revenue"
        ]
        return revenue or 0

    def end_trail(self):
        """
        End trail when the trail duration is reached
        """
        if self.on_trial:
            self.subscription.trail_duration = None
            self.subscription.save()
            self.on_trial = False
            self.deactivate()
            self.save()

    def trail_days_left(self):
        """
        Calculate the number of days left for the trail to end
        """
        if self.on_trial:
            trail_end_date = self.created + timedelta(days=self.trail_duration)
            days_left = (trail_end_date - datetime.now().date()).days
            # update the duration
            self.trail_duration=days_left
            # update duration and end trail then deactivate service
            if days_left == 0:
                self.on_trial = False
                self.deactivate()
                self.save()
            return days_left
        else:
            return None

    def upgrade(self, plan):
        """
        Iterate over the plans and then select a plan to upgrade and update the subscription
        """
        self.type = plan
        self.save()

    def downgrade(self):
        """
        Downgrade plan
        """
        pass

    def add_subscription(self):
        """
        if user upgrades service from trail create a subscription
        """
        if self.on_trial == True:
            subscription = self.subscription.objects.create()
            self.subscription.get_product_type("tenant")
            self.save()


@receiver(post_save, sender=Tenant)
def start_trial(sender, instance, created, **kwargs):
    """
    Automatically start a trial when a tenant is created
    """
    if created:
        if instance.owner.tenants.count() > 1:
            instance.on_trial = False
            instance.trail_duration = 0
        else:
            instance.on_trial = True
            instance.trail_duration = 30
        if instance.subscription:
        
            instance.subscription.status = "active"
            instance.subscription.cycle = "monthly"
            instance.subscription.subscription_duration = instance.trail_duration
            instance.subscription.save()
        instance.save()


class DomainManager(models.Manager):
    pass


class Domain(DomainMixin):
    is_custom = models.BooleanField(default=False)
    objects = DomainManager()

    def __str__(self):
        return self.domain

multitenancy/order/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from account.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from multitenancy.admin.views.baseViews import AdminTemplateView, AdminCreateView
from rest_framework import viewsets

from multitenancy.order.models import Order, Coupon
from multitenancy.order.serializers import CouponSerializer, OrdersSerializer
from multitenancy.order.form import CouponForm


class OdersViewSet(viewsets.ModelViewSet):
    model = Order
    serializer_class = OrdersSerializer
    queryset = Order.objects.all()


class CouponViewSet(viewsets.ModelViewSet):
    model = Coupon
    serializer_class = CouponSerializer
    queryset = Coupon.objects.all()


class OrderIndexView(AdminTemplateView):
    template_name = "multitenancy/order/order_index.html"


class OrdersListView(LoginRequiredMixin, AdminTemplateView):

    template_name = "multitenancy/order/orders_list.html"


class CouponListView(LoginRequiredMixin, AdminTemplateView):

    template_name = "multitenancy/order/coupon_list.html"


class CreateCouponView(LoginRequiredMixin, AdminCreateView):
    model = Coupon
    form_class = CouponForm
    success_url = reverse_lazy("coupon_list", urlconf="multitenancy.urls")
    template_name = "multitenancy/order/create_coupon.html"

    # print logs
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        print(form.errors)
        return super().form_valid(form)

    def form_invalid(self, form: BaseModelForm) -> HttpResponse:
        print(form.errors)
        return super().form_invalid(form)

multitenancy/templates/multitenancy/admin/adminUser/create_customer.html
{% extends "multitenancy/admin/base.html" %}
{% load bootstrap4 %}

{% block page_title %}Create Customer{% endblock page_title %}

{%block breadcrumbs%}
<li class="breadcrumb-item " ><a href="{% url 'customer_list' %}">Customers</a></li>

<li class="breadcrumb-item active">Create Customer</li>
{% endblock%}


{% block main_content %}

<!-- Main content -->
<section class="content">
    <div class="container text-dark">
        <form method="POST" enctype="multipart/form-data">

            <!-- Security token -->
            {% csrf_token %}
        
            
            {% bootstrap_field form.first_name %}
            {% bootstrap_field form.last_name %}
            {% bootstrap_field form.username %}
            {% bootstrap_field form.password %}
            {% bootstrap_field form.email %}
            
            
            <input type="submit" class="btn btn-info" value="Submit">
            <a class="btn btn-danger text-light" href="{% url "customer_list" %}" >Cancel</a>
        </form>
        

    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock main_content %}

{%block custom_js%}

{%endblock%}

multitenancy/templates/multitenancy/admin/adminUser/create_tenant_type.html
{% extends "multitenancy/admin/base.html" %}
{% load bootstrap4 %}

{% block page_title %}Create Tenant Templates{% endblock page_title %}

{%block breadcrumbs%}
<li class="breadcrumb-item " ><a href="{% url 'tenant_list' %}">Tenants</a></li>

<li class="breadcrumb-item active">Create Tenant Templates</li>
{% endblock%}


{% block main_content %}

<!-- Main content -->
<section class="content">
    <div class="container text-dark">
        <form method="POST" enctype="multipart/form-data">

            <!-- Security token -->
            {% csrf_token %}
        
            
            {% bootstrap_field form.name %}
            
            
            <input type="submit" class="btn btn-info" value="Submit">
            <a class="btn btn-danger text-light" href="{% url "create_tenant_type" %}" >Cancel</a>
        </form>
        

    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock main_content %}

{%block custom_js%}

{%endblock%}

multitenancy/templates/multitenancy/admin/adminUser/index.html
{% extends 'multitenancy/admin/base.html' %}
{%load static %}
{% block page_title %}Home{% endblock page_title %}
{% block main_content %}

    {% include "multitenancy/admin/adminUser/includes/dashboard.html" %}

{% endblock main_content %}

{% block custom_js %}

    
     <!-- ChartJS -->
     <script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>

<script>
  var activeDays = JSON.parse('{{ active_date|escapejs }}');
    var activeCount = JSON.parse('{{ active_count|escapejs }}');
    var inActiveCount = JSON.parse('{{ inactive_count|escapejs }}');
    $(document).ready(function(){
      
        var areaChartData = {
      labels  : activeDays,
      
      datasets: [
        {
          label               : 'Active Subscriptions',
          backgroundColor     : 'rgba(60,141,188,0.9)',
          borderColor         : 'rgba(60,141,188,0.8)',
          pointRadius          : false,
          pointColor          : '#3b8bba',
          pointStrokeColor    : 'rgba(60,141,188,1)',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(60,141,188,1)',
          data                : activeCount
        },
        {
          label               : 'Inactive Subscriptions',
          backgroundColor     : 'rgba(210, 214, 222, 1)',
          borderColor         : 'rgba(210, 214, 222, 1)',
          pointRadius         : false,
          pointColor          : 'rgba(210, 214, 222, 1)',
          pointStrokeColor    : '#c1c7d1',
          pointHighlightFill  : '#fff',
          pointHighlightStroke: 'rgba(220,220,220,1)',
          data                : inActiveCount
        },
      ]
    }

    


        //-------------
        //- BAR CHART -
        //-------------
        var barChartCanvas = $('#barChart').get(0).getContext('2d')
        var barChartData = jQuery.extend(true, {}, areaChartData)
        var temp0 = areaChartData.datasets[0]
        var temp1 = areaChartData.datasets[1]
        barChartData.datasets[1] = temp1
        barChartData.datasets[0] = temp0
    
        var barChartOptions = {
          responsive              : true,
          maintainAspectRatio     : false,
          datasetFill             : false
        }
    
        var barChart = new Chart(barChartCanvas, {
          type: 'bar', 
          data: barChartData,
          options: barChartOptions
        })
    })


     // Get context with jQuery - using jQuery's .get() method.
    var pieData        = {
      labels: [
          'Chrome', 
          'IE',
          'FireFox', 
          'Safari', 
          'Opera', 
          'Navigator', 
      ],
      datasets: [
        {
          data: [700,500,400,600,300,100],
          backgroundColor : ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc', '#d2d6de'],
        }
      ]
    }
    

     //-------------
    //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    var pieOptions     = {
      maintainAspectRatio : false,
      responsive : true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    var pieChart = new Chart(pieChartCanvas, {
      type: 'pie',
      data: pieData,
      options: pieOptions      
    })

      </script>

{% endblock custom_js %}
    

multitenancy/templates/multitenancy/admin/adminUser/subscription_list.html
{% extends "multitenancy/admin/base.html" %}


{% block page_title %}Manage Subscriptions{% endblock page_title %}
{%block breadcrumbs%}

<li class="breadcrumb-item active">Subscriptions</li>
{% endblock%}


{% block main_content %}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- /.row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title text-dark">Subscription Details</h3>

                        <div class="card-tools">
                            <form method="get" id="filter-form" class="input-group input-group-md" style="width: 200px;">
                                <input type="number" step="any" id="id_id" name="id" class="form-control float-right"
                                    placeholder="Search subscriptions">
                                <div class="input-group-append">
                                    <button type="submit" id="" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                            <form />
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body text-dark table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <!-- <th>Schema Name</th> -->
                                    <th>Slug</th>
                                    <th>Name</th>
                                    
                                    <th>Type</th>
                                    <th>Date Created</th>
                                    <th>Date Modified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {%if filter.qs %}
                                {% for tenant in filter.qs%}
                                <tr>
                                    <td>{{tenant.id}}</td>
                                    <!-- <td>{{tenant.schema_name}}</td> -->
                                    <td>{{tenant.slug}}</td>
                                    <td>{{tenant.name}}</td>
                                    <td>{{tenant.type}}</td>
                                    

                                    <td>{{tenant.created}}</td>
                                    <td>{{tenant.modified}}</td>
                                    {% if tenant.schema_name != "public" %}
                                    <th> <a name="" id="" class="btn btn-success text-light" href="{% url 'update_template' tenant.pk %}"
                                            role="button"><i class="fas fa-edit"></i> Edit</a> 
                                            
                                            <a name="" id="" class="btn btn-danger text-light" href="{% url 'delete_tenant' tenant.pk %}"
                                            role="button"><i class="fas fa-trash"></i> Delete</a> 
                                    </th>
                                        {% endif %}

                                    {% endfor %}
                                    {%else%}
                                    <td>There are no records to display</td>
                                    {%endif%}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        <!-- /.row -->


    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock main_content %}

{%block custom_js%}
<script>
    let filter = document.getElementById("filter-form")
    filter.addEventListener("submit", ()=>{
        alert("submit")
    })
    
</script>
{%endblock%}