multitenancy/teams/urls.py
from django.urls import re_path

from . import views

app_name = "pinax_teams"


urlpatterns = [
    # overall
    re_path(r"^$", views.TeamListView.as_view(), name="team_list"),
    re_path(r"^:create/$", views.TeamCreateView.as_view(), name="team_create"),

    # team specific
    re_path(r"^(?P<slug>[\w\-]+)/$", views.team_detail, name="team_detail"),
    re_path(r"^(?P<slug>[\w\-]+)/join/$", views.team_join, name="team_join"),
    re_path(r"^(?P<slug>[\w\-]+)/leave/$", views.team_leave, name="team_leave"),
    re_path(r"^(?P<slug>[\w\-]+)/apply/$", views.team_apply, name="team_apply"),
    re_path(r"^(?P<slug>[\w\-]+)/edit/$", views.team_update, name="team_edit"),
    re_path(r"^(?P<slug>[\w\-]+)/manage/$", views.TeamManageView.as_view(), name="team_manage"),

    # membership specific
    re_path(r"^(?P<slug>[\w\-]+)/ac/users-to-invite/$", views.autocomplete_users, name="team_autocomplete_users"),  # noqa
    re_path(r"^(?P<slug>[\w\-]+)/invite-user/$", views.TeamInviteView.as_view(), name="team_invite"),
    re_path(r"^(?P<slug>[\w\-]+)/members/(?P<pk>\d+)/revoke-invite/$", views.team_member_revoke_invite, name="team_member_revoke_invite"),  # noqa
    re_path(r"^(?P<slug>[\w\-]+)/members/(?P<pk>\d+)/resend-invite/$", views.team_member_resend_invite, name="team_member_resend_invite"),  # noqa
    re_path(r"^(?P<slug>[\w\-]+)/members/(?P<pk>\d+)/promote/$", views.team_member_promote, name="team_member_promote"),  # noqa
    re_path(r"^(?P<slug>[\w\-]+)/members/(?P<pk>\d+)/demote/$", views.team_member_demote, name="team_member_demote"),  # noqa
    re_path(r"^(?P<slug>[\w\-]+)/members/(?P<pk>\d+)/remove/$", views.team_member_remove, name="team_member_remove"),  # noqa

    re_path(r"^accept/(?P<pk>\d+)/$", views.team_accept, name="team_accept"),
    re_path(r"^reject/(?P<pk>\d+)/$", views.team_reject, name="team_reject"),
]

multitenancy/urls.py
from django.urls import path, include

# from django.conf.urls import url
from .admin import team_urls
from .admin import customer_urls
from .admin import urls as admin_urls
from .profiles import urls as profile_urls
from .subscriptions import urls as subscription_urls
from .users import urls as users_urls
from .apps import urls as apps_urls
from .settings import urls as settings_urls
from .billing import urls as billing_urls
from .order import urls as order_urls
from . import api


urlpatterns = [
    path("admin/", include(admin_urls)),
    path("admin/", include(users_urls)),
    path("admin/", include(apps_urls)),
    path("admin/", include(subscription_urls)),
    path("admin/", include(billing_urls)),
    path("admin/", include(order_urls)),
    path("admin/", include(settings_urls)),
    path("dashboard/", include(customer_urls)),
    path("admin/", include(team_urls)),
    path("admin/profiles/", include(profile_urls)),
    path("api/", include(api)),
]

multitenancy/admin/views/baseViews.py
from django.views.generic import TemplateView, ListView, DeleteView, View, CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.template.loader import get_template
from django.http import Http404, HttpResponseForbidden, HttpResponseNotFound
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from multitenancy.admin.decorators import allowed_users





class AdminView(UserPassesTestMixin, View):
    redirect_field_name = 'next'
    def test_func(self):
        """
        Checks if the user type is 'Admin'.
        """
        return self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

class AdminCreateView(UserPassesTestMixin, CreateView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

class AdminDetailView(UserPassesTestMixin, DetailView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class AdminUpdateView(UserPassesTestMixin, UpdateView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)
    
    def get(self, request, *args, **kwargs):
        self.object = None
        return super().get(request, *args, **kwargs)


class AdminDeleteView(UserPassesTestMixin, DeleteView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class AdminListView(UserPassesTestMixin, ListView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)
    


class AdminTemplateView(UserPassesTestMixin, TemplateView):
    redirect_field_name = 'next'

    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class StaffCreateView(UserPassesTestMixin, CreateView):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Staff'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class StaffUpdateView(UserPassesTestMixin, UpdateView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class StaffDeleteView(UserPassesTestMixin, DeleteView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class StaffListView(UserPassesTestMixin, ListView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

class StaffTemplateView(UserPassesTestMixin, TemplateView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class TeamDetailView(UserPassesTestMixin, DetailView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class TeamCreateView(UserPassesTestMixin, CreateView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class TeamUpdateView(UserPassesTestMixin, UpdateView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class TeamDeleteView(UserPassesTestMixin, DeleteView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)


class TeamListView(UserPassesTestMixin, ListView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

class TeamTemplateView(UserPassesTestMixin, TemplateView):
    redirect_field_name = 'next'
    def test_func(self):
        return  self.request.user.is_authenticated and self.request.user.type == 'Staff' or self.request.user.is_authenticated and self.request.user.type == 'Admin'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)
    

class CustomerView(UserPassesTestMixin, View):
    redirect_field_name = 'next'
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.type == 'Customer'
    
    def handle_no_permission(self):
        context = {'user': self.request.user}
        template = get_template('permission_denied.html')
        html = template.render(context, request=self.request)
        return HttpResponseForbidden(html)

class CustomerTemplateView(UserPassesTestMixin, TemplateView):
    redirect_field_name = 'next'
    def test_func(self):

multitenancy/templates/multitenancy/admin/base.html
{% load static %}
{% load multitenancy_tags %}
{% load i18n %}
{% load saved_queries %}
{% load load_helpdesk_settings %}
{% with request|load_helpdesk_settings as helpdesk_settings %}
    {% with user|saved_queries as user_saved_queries_ %}
        <!DOCTYPE html>
        <html class="">
            <head>
                <meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                {% get_company_details as details %}
                <title>Dashboard | {{ details.info.company_name }}</title>
                <!-- Tell the browser to be responsive to screen width -->
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <!-- Font Awesome -->
                <link rel="stylesheet" href="{% static "plugins/fontawesome/css/all.min.css" %}">
                <!-- Ionicons -->
                <link rel="stylesheet"
                      href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
                <link rel="stylesheet" href="{% static "plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" %}">
                <!-- Theme style -->
                <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
                <!-- DataTables -->
                <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}">
                <link rel="stylesheet" href="{% static "plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}">
                <link rel="stylesheet" href="{% static "plugins/sweetalert2/sweetalert2.min.css" %}">
                {#% include 'helpdesk/base-head.html' %#}
                {% block custom_css %}{% endblock %}
                {% block custom_head_js %}
                {% endblock custom_head_js %}
                {% block helpdesk_head %}{% endblock %}
                <!-- Google Font: Source Sans Pro -->
                <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
                      rel="stylesheet">
            </head>
            <body class="sidebar-mini bg-dark layout-fixed sidebar-collapse accent-navy  sidebar-closed"
                  style="height: auto">
                <div class="wrapper">
                    <!-- Navbar -->
                    <nav class="main-header navbar navbar-expand sticky-top navbar-dark navbar-navy">
                        <!-- Left navbar links -->
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                            </li>
                            <!--
                    <li class="nav-item d-none d-sm-inline-block">
                        <a href="#" class="nav-link">Contact</a>
                    </li>
                    -->
                        </ul>
                        <!-- SEARCH FORM -->
                        <form class="form-inline ml-3">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar"
                                       type="search"
                                       placeholder="Search"
                                       aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        {#% include "multitenancy/admin/adminUser/includes/notifications.html" %#}
                        <!-- Right navbar links -->
                        {% include "multitenancy/admin/navbar.html" %}
                    </nav>
                    <!-- /.navbar -->
                    {% if user.type == 'Admin' %}
                        {% include "multitenancy/admin/adminUser/includes/sidebar_template.html" with user=user id=id %}
                    {% elif user.type == 'Staff' %}
                        {% include "multitenancy/admin/teamUser/includes/sidebar_template.html" with user=user id=id %}
                    {% else %}
                        {% include "multitenancy/admin/publicUser/includes/sidebar_template.html" with user=user id=id %}
                    {% endif %}
                    <!-- Content Wrapper. Contains page content -->
                    <div class="content-wrapper">
                        <!-- Content Header (Page header) -->
                        <div class="content-header">
                            <div class="container-fluid">
                                <div class="row mb-2">
                                    <div class="col-sm-6">
                                        <h1 class="text-dark">
                                            {% block page_title %}
                                            {% endblock page_title %}
                                        </h1>
                                    </div>
                                    <!-- /.col -->
                                    <div class="col-sm-6">
                                        <ol class="breadcrumb float-sm-right">
                                            {% if user.type == 'Admin' %}
                                                <li class="breadcrumb-item">
                                                    <a href="{% url "admin_dashboard" %}">Home</a>
                                                </li>
                                            {% elif user.type == 'Staff' %}
                                                <li class="breadcrumb-item">
                                                    <a href="{% url "team_dashboard" %}">Home</a>
                                                </li>
                                            {% else %}
                                                <li class="breadcrumb-item">
                                                    <a href="{% url "customer_dashboard" %}">Home</a>
                                                </li>
                                            {% endif %}
                                            {% block breadcrumbs %}{% endblock %}
                                        </ol>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <!-- /.row -->
                            </div>
                            <!-- /.container-fluid -->
                        </div>
                        <!-- /.content-header -->
                        {% block main_content %}
                        {% endblock main_content %}
                    </div>
                    <!-- /.content-wrapper -->
                    {% include "multitenancy/admin/footer.html" %}
                    <!-- Control Sidebar -->
                    <aside class="control-sidebar control-sidebar-dark">
                        <!-- Control sidebar content goes here -->
                    </aside>
                    <!-- /.control-sidebar -->
                </div>
                <!-- ./wrapper -->
                <!-- jQuery -->
                <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
                <!-- Bootstrap 4 -->
                <script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
                <script src="{% static "plugins/datatables/jquery.dataTables.min.js" %}"></script>
                <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
                <script src="{% static "plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
                <script src="{% static "plugins/datatables-responsive/js/dataTables.responsive.min.js" %}"></script>
                <script src="{% static "plugins/datatables-responsive/js/responsive.bootstrap4.min.js" %}"></script>
                <script src="{% static "dist/js/adminlte.min.js" %}"></script>
                <script src="{% static "plugins/sweetalert2/sweetalert2.all.min.js" %}"></script>
                <!-- SweetAlert2 -->
                {% load sweetify %}
                {% sweetify %}
                <!-- DataTables -->
                {% block custom_js %}
                {% endblock custom_js %}
            </body>
        </html>
    {% endwith %}
{% endwith %}

multitenancy/templates/multitenancy/admin/footer.html
{% load multitenancy_tags %}
{% get_company_details as details %}
<footer class="main-footer text-center" >
    <strong class="text-center">Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="{{details.info.website}}">{{details.info.company_name}}</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">

    </div>
</footer>

multitenancy/templates/multitenancy/admin/navbar.html
{% load static %}
{% load i18n helpdesk_staff %}
<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->

    <!-- Notifications Dropdown Menu -->
    {%if user.type == "Admin"%}
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="fas fa-cogs"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
            <a href="{% url 'pinax_teams:team_list'%} " class="dropdown-item">
                <i class="fas fa-envelope mr-2"></i> Teams
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'update_address' %}" class="dropdown-item">
                <i class="fas fa-map-marker mr-2"></i> Address

            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'update_info' %}" class="dropdown-item">
                <i class="fas fa-file mr-2"></i> Company Details
            </a>
            <!-- <div class="dropdown-divider"></div>
            <a href="{#% url 'manage_tlds'%#}" class="dropdown-item">
                <i class="fas fa-globe mr-2"></i>View TLD's
            </a> -->
            <div class="dropdown-divider"></div>
            <a href="{% url 'plan_list'%}" class="dropdown-item">
                <i class="fas fa-list-ol mr-2"></i>View Plans
            </a>
            <!-- <div class="dropdown-divider"></div>
            <a href="{#% url 'product_list'%#}" class="dropdown-item">
                <i class="fas fa-gift mr-2"></i>View Products
            </a>
            
            <div class="dropdown-divider"></div>
            <a href="{#% url 'accounts_manager' %#}" class="dropdown-item">
                <i class="fas fa-users mr-2"></i> Accounts Manager
            </a> -->
            <div class="dropdown-divider"></div>
            <a href="{% url 'settings_index'%}" class="dropdown-item dropdown-footer">All Settings</a>
        </div>
    </li>
    {%endif%}
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="fas fa-globe"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
            <a href="{% url 'pinax_teams:team_list'%} " class="dropdown-item">
                English
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'update_address' %}" class="dropdown-item">
                Swahili

            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'update_info' %}" class="dropdown-item">
                Spanish
            </a>


        </div>
    </li>


</ul>




<ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
       

        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            {%if user.is_staff %}
            <a href="{% url 'profiles_detail' username=user.username %}" class="dropdown-item">
                <i class="fas fa-user mr-2"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            {%endif%}
            <a href="{% url 'account_settings'  %}" class="dropdown-item">
                <i class="fas fas fa-user-edit mr-2"></i> Account
            </a>
            <div class="dropdown-divider"></div>
            {% if helpdesk_settings.HELPDESK_NAVIGATION_ENABLED and user.is_authenticated or user|is_helpdesk_staff %}
            <a class="dropdown-item" href="{% url 'helpdesk:user_settings' %}"><i class="fas fa-fw fa-user-cog"></i>
                {% trans "User Settings" %}</a>
            <a class="dropdown-item" href='{% url 'helpdesk:rss_index' %}'><i class="fas fa-fw fa-rss-square"></i>
                {% trans "RSS Feeds" %}</a>
            {% if helpdesk_settings.HELPDESK_SHOW_CHANGE_PASSWORD and user.has_usable_password %}
            <a class="dropdown-item" href="{% url 'helpdesk:password_change' %}"><i
                    class="fas fa-fw fa-user-secret"></i> {% trans "Change password" %}</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            {% if user.is_superuser %}
            <a class="dropdown-item" href='{% url 'helpdesk:system_settings' %}'><i class="fas fa-fw fa-cogs"></i>
                {% trans "System Settings" %}</a>
            <div class="dropdown-divider"></div>
            {% endif %}
            {% endif %}
            <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fas fa-fw fa-sign-out-alt"></i>
                {% trans "Logout" %}</a>
        </div>
    </li>




</ul>